name: Branch naming test

on:
  push:

jobs:
  limit-to-certain-branch:
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        branch: [ dev, test, prod ]

    steps:
      - name: Echo stage name
        run: echo "Running for ${{ matrix.branch }}"

      - name: Calc branch name
        run: echo "CALC_BRANCH=refs/heads/stage/${{ matrix.branch }}" >> "$GITHUB_ENV"

      - name: Echo branch name
        run: echo ${GITHUB_REF##*/}

      - name: Echo calc branch
        run: echo ${{ env.CALC_BRANCH }}

      - name: Do important stuff only for branch
        run: echo "Something very important here"
        if: github.event_name == 'push' && github.ref == env.CALC_BRANCH
