name: Branch naming test

on:
  push:
    branches:
      - stage/dev
      - stage/test
  pull_request:

jobs:
  limit-to-certain-branch:
    runs-on: ubuntu-20.04
    name: "My staged jobs"
    defaults:
      run:
        shell: bash

#    strategy:
#      matrix:
#        branch: [ dev, test, prod ]
#      max-parallel: 1
    steps:
      - name: Echo stage name
        run: echo "Running for ${{ matrix.branch }}"

      - name: Calc branch name
        run: echo "CALC_BRANCH=refs/heads/stage/${{ matrix.branch }}" >> "$GITHUB_ENV"

      - name: Echo branch name
        run: echo ${GITHUB_REF##*/}

      - name: Echo GITHUB Ref
        run: echo $GITHUB_REF

      - name: Echo Branch Base Parsed
        run: |
          echo $GITHUB_BASE_REF
          echo ${GITHUB_BASE_REF##*/}

      - name: Echo Head Base Parsed
        run: |
          echo $GITHUB_HEAD_REF
          echo ${GITHUB_HEAD_REF##*/}

#      - name: Echo calc branch
#        run: echo ${{ env.CALC_BRANCH }}

      - name: Do important stuff only for branch
        run: echo "Something very important here"
        if: github.event_name == 'push' && github.ref == github.base_ref
